name: color_logger
description: Simple way to output timestamped logs messages with color in stdout.
version: 1.0.2
homepage: https://github.com/andrelec1/color_logger
repository: https://github.com/andrelec1/color_logger

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

dependencies: 
  ansicolor: ^2.0.1
